apiVersion: v1
kind: Template
metadata:
  name: sdgesi-deployment-template
  annotations:
    description: "Template for generate SDGESI Fuse deployment artifacts"
    iconClass: "icon-rh-integration"
    openshift.io/display-name: SDGESI Spring Boot Deployment Profile
    openshift.io/provider-display-name: SDGESI
    tags: "fuse,sdgesi,deployment"
labels:
  template: sdgesi-deployment-template
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  data:
    application.properties: |
      environment=Integration
      color=yellow
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
        - image: ${IMAGE_NAMESPACE}/${IMAGE}
          name: spring-app
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
            name: jolokia
          resources: {}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/info
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /deployments/config
              name: volume-${NAME}
        volumes:
          - configMap:
              defaultMode: 420
              name: ${NAME}
            name: volume-${NAME}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-app
        from:
          kind: ImageStreamTag
          name: ${IMAGE}
          namespace: ${IMAGE_NAMESPACE}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: jolokia
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${NAME}
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
      - conditions:
        - status: 'True'
          type: Admitted
parameters:
  - name: NAME
    description: The name assigned to all of the objects defined in this template.
    displayName: Application Name
    required: true
  - name: IMAGE
    description: The name assigned of the image steam
    displayName: Image Stream name
    required: true
  - name: IMAGE_NAMESPACE
    description: The name assigned of the image steam
    displayName: Image Stream name
    value: build
